name: premiertraslados_appchofer_nuevo
description: "A new Flutter project."
publish_to: 'none'
version: 17.0.1+18

environment:
  sdk: '>=3.4.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # Firebase
  firebase_core: ^2.32.0
  firebase_auth: ^4.20.0
  cloud_firestore: ^4.17.5
  
  # Funcionalidades
  location: ^6.0.2
  permission_handler: 11.3.1
  geolocator: ^12.0.0
  url_launcher: ^6.3.0
  intl: ^0.19.0 # <-- Paquete para formatear fechas y horas

  # Notificaciones y Versiones
  firebase_messaging: ^14.9.4
  flutter_local_notifications: ^17.2.4
  firebase_remote_config: ^4.4.7
  package_info_plus: ^8.0.0
  shared_preferences: ^2.2.3
  firebase_crashlytics: ^3.5.7
  cloud_functions: ^4.7.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
